import type { DeepResearchJobResult } from '../api';

async function getLogoDataUri(): Promise<string> {
  try {
    const resp = await fetch('/north-signal-logo-transparent.png');
    const blob = await resp.blob();
    return new Promise((resolve) => {
      const reader = new FileReader();
      reader.onloadend = () => resolve(reader.result as string);
      reader.readAsDataURL(blob);
    });
  } catch {
    return ''; // Fallback: no logo
  }
}

export async function downloadReportAsPdf(result: DeepResearchJobResult) {
  const { report, resultText, ticker, researchType, completedAt } = result;
  const logoDataUri = await getLogoDataUri();

  const dateStr = completedAt
    ? new Date(completedAt).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' })
    : new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });

  // Always use light colors for print — browsers strip backgrounds by default
  const textPrimary = '#1a1a1a';
  const textSecondary = '#6b7280';
  const textMuted = '#9ca3af';
  const textBody = '#374151';
  const border = '#e5e7eb';
  const cardBg = '#f9fafb';
  const green = '#00c805';
  const blue = '#3b82f6';
  const red = '#ef4444';

  const escHtml = (s: string) =>
    s.replace(/&/g, '&amp;').replace(/</g, '&lt;').replace(/>/g, '&gt;').replace(/"/g, '&quot;');

  // Build body content
  let body = '';

  // Header
  body += `
    <div class="header">
      <div class="logo-row">
        ${logoDataUri ? `<img class="logo-img" src="${logoDataUri}" alt="N" />` : `<div class="logo-n">N</div>`}
        <div>
          <div class="title">NALA AI Deep Research</div>
          <div class="subtitle">${escHtml(researchType.charAt(0).toUpperCase() + researchType.slice(1))} Analysis${ticker ? ` · ${escHtml(ticker)}` : ''} · ${escHtml(dateStr)}</div>
        </div>
      </div>
    </div>`;

  if (report) {
    // Executive Summary
    body += `
    <div class="section-card">
      <h3 class="section-label">Executive Summary</h3>
      <p class="body-text">${escHtml(report.executiveSummary)}</p>
    </div>`;

    // Bull / Base / Bear
    body += `<div class="cases-grid">`;
    body += caseCard('Bull Case', green, report.bullCase, escHtml);
    body += caseCard('Base Case', blue, report.baseCase, escHtml);
    body += caseCard('Bear Case', red, report.bearCase, escHtml);
    body += `</div>`;

    // Key Risks + Key Catalysts
    if (report.keyRisks.length > 0 || report.keyCatalysts.length > 0) {
      body += `<div class="two-col">`;
      if (report.keyRisks.length > 0) {
        body += bulletCard('Key Risks', report.keyRisks, red, escHtml);
      }
      if (report.keyCatalysts.length > 0) {
        body += bulletCard('Key Catalysts', report.keyCatalysts, green, escHtml);
      }
      body += `</div>`;
    }

    // Valuation
    body += `
    <div class="section-card">
      <h3 class="section-label">Valuation — ${escHtml(report.valuation.method)}</h3>
      <p class="body-text">${escHtml(report.valuation.summary)}</p>
      ${report.valuation.comparables.length > 0 ? `
        <div class="comparables">
          ${report.valuation.comparables.map(t => `<span class="comp-chip">${escHtml(t)}</span>`).join('')}
        </div>` : ''}
    </div>`;

    // Confidence Notes
    if (report.confidenceNotes) {
      body += `
      <div class="confidence-card">
        <h4 class="confidence-label">Confidence Notes</h4>
        <p class="confidence-text">${escHtml(report.confidenceNotes)}</p>
      </div>`;
    }

    // Citations
    if (report.citations.length > 0) {
      body += `
      <div class="section-card">
        <h3 class="section-label">Sources (${report.citations.length})</h3>
        <div class="citations">
          ${report.citations.map((cite, i) => `
            <div class="citation">
              <span class="cite-num">${i + 1}.</span>
              <div>
                <a href="${escHtml(cite.url)}" class="cite-link">${escHtml(cite.title)}</a>
                ${cite.snippet ? `<p class="cite-snippet">${escHtml(cite.snippet)}</p>` : ''}
              </div>
            </div>`).join('')}
        </div>
      </div>`;
    }
  } else if (resultText) {
    // Fallback raw text
    body += `
    <div class="section-card">
      <pre class="raw-text">${escHtml(resultText)}</pre>
    </div>`;
  }

  // Footer
  body += `
    <div class="footer">
      <p class="disclaimer">This report is generated by NALA AI for informational purposes only and does not constitute financial advice. Always conduct your own due diligence before making investment decisions.</p>
      <p class="powered-by">Generated by NALA AI · Powered by Google Deep Research (Gemini)</p>
    </div>`;

  const html = `<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <title>NALA Research Report${ticker ? ` — ${ticker}` : ''}</title>
  <style>
    *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
    body {
      font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, 'Helvetica Neue', Arial, sans-serif;
      background: #ffffff;
      color: ${textPrimary};
      padding: 40px;
      max-width: 800px;
      margin: 0 auto;
      line-height: 1.6;
    }
    .header { margin-bottom: 32px; padding-bottom: 20px; border-bottom: 1px solid ${border}; }
    .logo-row { display: flex; align-items: center; gap: 14px; }
    .logo-img {
      width: 40px; height: 40px; border-radius: 10px;
      object-fit: contain;
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }
    .logo-n {
      width: 40px; height: 40px; border-radius: 10px;
      background: ${green}; color: #fff;
      font-size: 22px; font-weight: 800;
      display: flex; align-items: center; justify-content: center;
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }
    .title { font-size: 18px; font-weight: 700; color: ${textPrimary}; }
    .subtitle { font-size: 12px; color: ${textSecondary}; margin-top: 2px; }
    .section-card {
      padding: 20px; border-radius: 12px;
      background: ${cardBg}; border: 1px solid ${border};
      margin-bottom: 16px; page-break-inside: avoid;
    }
    .section-label {
      font-size: 11px; font-weight: 600; text-transform: uppercase;
      letter-spacing: 0.05em; color: ${textSecondary}; margin-bottom: 10px;
    }
    .body-text { font-size: 13px; color: ${textPrimary}; white-space: pre-line; line-height: 1.7; }
    .cases-grid { display: grid; grid-template-columns: repeat(3, 1fr); gap: 12px; margin-bottom: 16px; }
    .case-card {
      padding: 16px; border-radius: 12px;
      background: ${cardBg}; border: 1px solid ${border};
      border-left-width: 3px; page-break-inside: avoid;
    }
    .case-label { font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.05em; margin-bottom: 8px; }
    .case-text { font-size: 12px; color: ${textBody}; white-space: pre-line; line-height: 1.6; }
    .two-col { display: grid; grid-template-columns: repeat(2, 1fr); gap: 12px; margin-bottom: 16px; }
    .bullet-card {
      padding: 16px; border-radius: 12px;
      background: ${cardBg}; border: 1px solid ${border};
      page-break-inside: avoid;
    }
    .bullet-label {
      font-size: 11px; font-weight: 600; text-transform: uppercase;
      letter-spacing: 0.05em; margin-bottom: 10px;
    }
    .bullet-list { list-style: none; padding: 0; }
    .bullet-list li {
      font-size: 12px; color: ${textBody};
      line-height: 1.6; padding: 3px 0; padding-left: 14px; position: relative;
    }
    .bullet-list li::before { content: '•'; position: absolute; left: 0; color: ${textMuted}; }
    .comparables { display: flex; flex-wrap: wrap; gap: 6px; margin-top: 12px; }
    .comp-chip {
      padding: 2px 10px; border-radius: 6px; font-size: 11px; font-weight: 500;
      background: rgba(0,200,5,0.1); color: ${green};
      -webkit-print-color-adjust: exact; print-color-adjust: exact;
    }
    .confidence-card {
      padding: 16px; border-radius: 10px; margin-bottom: 16px;
      background: rgba(59,130,246,0.05);
      border: 1px solid rgba(59,130,246,0.15);
      page-break-inside: avoid;
    }
    .confidence-label { font-size: 11px; font-weight: 600; color: ${blue}; margin-bottom: 6px; }
    .confidence-text { font-size: 12px; color: ${textSecondary}; line-height: 1.6; }
    .citations { display: flex; flex-direction: column; gap: 10px; }
    .citation { display: flex; gap: 8px; align-items: flex-start; }
    .cite-num { font-size: 10px; font-family: monospace; color: ${textSecondary}; width: 18px; text-align: right; flex-shrink: 0; margin-top: 2px; }
    .cite-link { font-size: 12px; font-weight: 500; color: ${green}; text-decoration: none; }
    .cite-snippet { font-size: 11px; color: ${textMuted}; margin-top: 3px; line-height: 1.5; }
    .raw-text { font-size: 12px; white-space: pre-wrap; font-family: monospace; color: ${textBody}; line-height: 1.6; }
    .footer {
      margin-top: 32px; padding-top: 16px; border-top: 1px solid ${border};
    }
    .disclaimer { font-size: 10px; color: ${textMuted}; line-height: 1.5; }
    .powered-by { font-size: 10px; color: #d1d5db; margin-top: 6px; }

    @media print {
      body { padding: 20px; }
      @page { margin: 15mm; size: A4; }
      .section-card, .case-card, .bullet-card, .confidence-card { page-break-inside: avoid; }
      .cases-grid { page-break-inside: avoid; }
      a { color: ${green} !important; }
    }
  </style>
</head>
<body>${body}</body>
</html>`;

  const printWindow = window.open('', '_blank');
  if (!printWindow) return;
  printWindow.document.write(html);
  printWindow.document.close();
  printWindow.addEventListener('load', () => {
    printWindow.print();
  });
}

function caseCard(label: string, color: string, text: string, esc: (s: string) => string) {
  return `
    <div class="case-card" style="border-left-color: ${color};">
      <div class="case-label" style="color: ${color};">${esc(label)}</div>
      <div class="case-text">${esc(text)}</div>
    </div>`;
}

function bulletCard(label: string, items: string[], color: string, esc: (s: string) => string) {
  return `
    <div class="bullet-card">
      <div class="bullet-label" style="color: ${color};">${esc(label)}</div>
      <ul class="bullet-list">
        ${items.map(item => `<li>${esc(item)}</li>`).join('')}
      </ul>
    </div>`;
}
